apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: django-pvc

spec:

  accessModes:

    - ReadWriteMany

  storageClassName: nfs-client

  resources:

    requests:

      storage: 500Mi

