kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: vlasis/react-docker
        ports:
        - containerPort: 80
        volumeMounts:
          - name: app-storage
            mountPath: /app/public
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: react-app-pvc

